{{- if .Values.onlyoffice.deploy }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-oo-postgresql
spec:
{{- if .Values.onlyoffice.volume.storageClassName }}
  storageClassName:  {{ .Values.onlyoffice.volume.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.onlyoffice.volume.size }}
{{- end }}

