apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-oo-postgresql
spec:
  storageClassName:  {{ .Values.onlyoffice.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.onlyoffice.volume.size }}