{{- if and (not (.Values.onlyoffice).secretname ) ( (.Values.onlyoffice).deploy) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-onlyoffice
data:
  onlyoffice-secret: {{ .Values.onlyoffice.secret | b64enc }}
---
{{- end }}