{{- if and .Values.onlyoffice.deploy (not .Values.onlyoffice.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-onlyoffice
data:
  onlyoffice-secret: {{ .Values.onlyoffice.secret | b64enc }}
---
{{- end }}
