{{- if not .Values.config.auth.adminPasswordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-admin
data:
  password: {{ .Values.config.auth.adminPassword | b64enc }}
---
{{- end }}

