{{- if not .Values.config.auth.adminPasswordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-admin
data:
  password: {{ .Values.config.auth.adminPassword | b64enc }}
---
{{- end }}


{{- if and (not (.Values.onlyoffice).secretname ) ( (.Values.onlyoffice).active) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-office
data:
  onlyoffice-secret: {{ .Values.onlyoffice.secret | b64enc }}
---
{{- end }}

{{- if and (not ((((.Values.config).auth).methods).oidc).clientSecretName ) ( ((((.Values.config).auth).methods).oidc).enabled ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser-quantum.fullname" . }}-oidc
data:
  oidc-secret: {{ .Values.config.auth.methods.oidc.clientSecret | b64enc }}
---
{{- end }}